### ISSUE TITLE
Session instantiation fails in synchronous code

### ISSUE THREAD

**Issue by lundybernard** [CanopySimulations/canopy-python#3]
https://github.com/CanopySimulations/canopy-python/blob/d1f0d3c3bb394c8d53e4af20e624593e732dbbec/canopy/session.py#L42

Calling `canopy.openapi_asyncio.ApiClient` in the `__init__` method causes an exception `RuntimeError: There is no current event loop in thread 'MainThread'.` when run from synchronous code.

```python
src/data_loaders/canopyclient.py:90: in _session
    session = Session(self._authentication_data)
../../miniconda3/envs/data_loaders/lib/python3.10/site-packages/canopy/session.py:43: in __init__
    self._async_client = canopy.openapi_asyncio.ApiClient(
../../miniconda3/envs/data_loaders/lib/python3.10/site-packages/canopy/openapi_asyncio/api_client.py:76: in __init__
    self.rest_client = rest.RESTClientObject(configuration)
../../miniconda3/envs/data_loaders/lib/python3.10/site-packages/canopy/openapi_asyncio/rest.py:65: in __init__
    connector = aiohttp.TCPConnector(
../../miniconda3/envs/data_loaders/lib/python3.10/site-packages/aiohttp/connector.py:767: in __init__
    super().__init__(
../../miniconda3/envs/data_loaders/lib/python3.10/site-packages/aiohttp/connector.py:234: in __init__
    loop = get_running_loop(loop)
../../miniconda3/envs/data_loaders/lib/python3.10/site-packages/aiohttp/helpers.py:287: in get_running_loop
    loop = asyncio.get_event_loop()
```

We cannot create a Session object in sychronous code to use `Session.sync_client`, without some ugly asyncio hacks.

I was able to work around the instantiation problem by making the async_client a lazy-loaded attribute...  but ran into further trouble because SerializeableValue uses the async_client exclusively: https://github.com/CanopySimulations/canopy-python/blob/d1f0d3c3bb394c8d53e4af20e624593e732dbbec/canopy/serializable_value.py#L17

There are likely other places where async_client is used explicitly, however fixing `Session`, and manually serializing my filter resolved my current issue.

**Comment by jamesthurley** [comment]
Can you share some information about your environment to help me reproduce the issue?

**Comment by lundybernard** [comment]
Sure, what information would be helpful?

I can provide a simplified use-case that demonstrates the problem:
```python
from functools import cached_property
from canopy import Session, AuthenticationData
from canopy.openapi import StudyApi


class CanopyClient:
    def __init__(
        self,
        tenant_id: str,
        username: str,
        password: str,
        client_id: str,
        client_secret: str,
    ):
        self._tenant_id = tenant_id
        self._client_id = client_id
        self._username = username
        self._password = password
        self._client_id = client_id
        self._client_secret = client_secret

    @cached_property
    def study_api(self):
        return StudyApi(self._session, self._tenant_id)

    @cached_property
    def _session(self):
        session = Session(self._authentication_data)
        session.authentication.authenticate()
        return session

    @cached_property
    def _authentication_data(self):
        return AuthenticationData(
            client_id=self._client_id,
            client_secret=self._client_secret,
            username=self._username,
            password=self._password,
        )


class StudyApi:
    def __init__(
        self, session, tenant_id: str,
    ):
        self._tenant_id = tenant_id
        self._session = session

    @cached_property
    def _study_api(self):
        return StudyApi(self._session.sync_client)
```

In this example, we are trying to work with a synchronous client, but as soon as we use `CanopyClient.study_api` it throws `RuntimeError: There is no current event loop in thread 'MainThread'`.

**Comment by jamesthurley** [comment]
Ok, I think I understand now. I was failing to reproduce the `RuntimeError` in various versions of Python. However, if I run the test on a new thread then I do get a `RuntimeError`. I see that `get_event_loop()` automatically creates an event loop on the main thread if there isn't one, which is why I didn't get it there.

**Comment by jamesthurley** [comment]
I've updated `canopy.Session` to lazily load the async client, and I've updated `canopy.SerializableValue` to use `sanitize_for_serialization` from the synchronous client rather than the async one, which should hopefully help you with the two issues you've mentioned above. These changes appear in version `8.35` of the library.

As you've noted, there are other places which use the `async_client` explicitly. This is by design, as the library is written to be non-blocking and to parallelize the downloads of study data using `asyncio`. However, if you do find other places where references to asyncio can be trivially removed (or deferred) like the ones above, feel free to request the changes.
